# Equity of attention

## Importing libraries

In [1]:
import os
import sys
import math

sys.path.append(os.path.join('..'))

In [2]:
import pandas as pd
import numpy as np

In [3]:
from models.ilpbased_eoa import ILPBasedEOA

## Preparing data

In [4]:
data_path = '../data'

In [5]:
data = pd.read_csv('../data/datasets/airbnb_Boston_listings.csv')
data.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_upd

First tested with random data, that is 20 integer numbers from 0 to 10 representing a ranking with relevance values

In [6]:
test_data = data['review_scores_rating'].fillna(0).to_numpy()
#test_data = np.array(np.random.rand(100) * 10, dtype=int)
test_data

array([4.95, 4.77, 4.79, ..., 0.  , 0.  , 0.  ])

Create the object for this ranking

In [7]:
test = ILPBasedEOA(test_data, 0, 5)

In [8]:
test.prepare(0.5, 5, 100, 1 * math.pow(10, -7))

In [9]:
test.start(1)

Prefiltering...
[ 778  937 2561  938 2562]
[ 778  937 2561  938 2562    4    0    2    3    1]
[7.780e+02 9.370e+02 2.561e+03 9.380e+02 2.562e+03 4.000e+00 0.000e+00
 2.000e+00 3.000e+00 1.000e+00]
Optimizing... iteration 0, ranking 0
Welcome to the CBC MILP Solver 
Version: devel 
Build Date: Nov 15 2020 

Starting solution of the Linear programming relaxation problem using Primal Simplex

Coin0506I Presolve 200 (0) rows, 10000 (0) columns and 20000 (0) elements
Clp1000I sum of infeasibilities 5.27584e-09 - average 2.63792e-11, 4 fixed columns
Coin0506I Presolve 200 (0) rows, 9996 (-4) columns and 19992 (-8) elements
Clp0000I Optimal - objective value 0
Clp0000I Optimal - objective value 0
Coin0511I After Postsolve, objective 0, infeasibilities - dual 0 (0), primal 0 (0)
Clp0000I Optimal - objective value 0
Clp0000I Optimal - objective value 0
Clp0000I Optimal - objective value 0
Clp0032I Optimal objective 0 - 0 iterations time 0.122, Idiot 0.11

Starting MIP optimization
Cgl0004I pro

In [11]:
grid = ""
for i, val in enumerate(test.mip_model.vars):
    grid += "1 " if val.x >= 0.99 else "0 "
    if (i + 1) % test.pref_n == 0:
        grid += "\n"
print(grid)

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 